cmake_minimum_required(VERSION 4.1)
project(codeforces)

set(CMAKE_CXX_STANDARD 23)

add_executable(codeforces main.cpp
        round_1119_div_3/minus_two.cpp
        yargu_2026_2027_binary_operations/a_2_in_the_power_of_n.cpp
        yargu_2026_2027_binary_operations/b_set_bit_value_to_0.cpp
        yargu_2026_2027_binary_operations/c_get_bit_value.cpp
        yargu_2026_2027_binary_operations/d_invert_bit.cpp
        yargu_2026_2027_binary_operations/e_print_byte.cpp
        yargu_2026_2027_binary_operations/f_xorinacci.cpp
        yargu_2026_2027_binary_operations/g_small_xor.cpp
        yargu_2026_2027_binary_operations/h_maximize_and.cpp
        yargu_2026_2027_binary_operations/i_pan_balance.cpp
        contest_11_09_2026/a_butterfly_collector.cpp
        yargu_2026_2027_binary_operations/j_restroom.cpp
        yargu_2026_2027_binary_operations/k_hide_and_seek.cpp
        yargu_2026_2027_binary_operations/l_dima_and_bad_xor.cpp
        yargu_2026_2027_binary_operations/m_maximum_and_bits.cpp
        yargu_2026_2027_binary_operations/n_bits.cpp)
